services:
  nmdviewer:
    image: ghcr.io/alexnmd/nmdviewer:latest
    ports:
      - "8080:8000"
    environment:
      NMDNS: "https://www.alex-nmd.net"
      CV_FILENAME: CV_Alexandre_Normand_2025.pdf
      INSTAGRAM_PROFILE: "https://www.instagram.com/alexxnmd/"
      GITHUB_PROFILE: "https://github.com/alexNMD"
    volumes:
      - /mnt/Armoire/projects_viewer:/app/nmd_project
      - ./documents:/app/documents
    container_name: nmdviewer
    restart: unless-stopped
