services:
  nmd_viewer:
    image: ghcr.io/alexnmd/nmd_viewer:latest
    ports:
      - 8080:8080
    environment:
      - PROJECTS_PATH=/media/Armoire/projects_viewer
      - APP_ENV=prod
    volumes:
      - /application/nmd-viewer:/nmd-viewer
      - /media/Armoire/projects_viewer:/media/Armoire/projects_viewer
    container_name: nmd_viewer
    restart: unless-stopped