services:
  nmdviewer:
    image: nmdviewer
    ports:
      - "8080:8000"
    environment:
      NMDNS: "https://www.alex-nmd.net"
      CV_FILENAME: CV_Alexandre_Normand_2025.pdf
      INSTAGRAM_URL: "https://www.instagram.com/alexxnmd/"
      GITHUB_URL: "https://github.com/alexNMD"
    volumes:
      - /mnt/Armoire/projects_viewer:/app/nmd_project
      - ./documents:/app/documents
    container_name: nmdviewer
    restart: unless-stopped
